repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-docstring-first
    -   id: check-merge-conflict

-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black

-   repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
    -   id: flake8
        args: [--max-line-length=88]
        #files: ^my_appname/|^test_suite_name/

-   repo: https://github.com/asottile/reorder_python_imports
    rev: v3.12.0
    hooks:
    -   id: reorder-python-imports
